export default Object.freeze({
  WELCOME_SCREEN: "WelcomeScreen",
  LOGIN_SCREEN: "LoginScreen",
  REGISTER_SCREEN: "RegisterScreen",
  AUTH_NAVIGATION: "Auth Nav",
  TAB_NAVIGATION: "Tab Nav",
  HOME_SCREEN: "Home Screen",
  ACCOUNT_SCREEN: "Account Screen",
  CART_SCREEN: "Cart Screen",
  SEARCH_SCREEN: "Seach Screen",
  PROFILE_SCREEN: "Profile Screen",
  USER_NAVIGATION: "User nav",
  ORDERS_SCREEN: "Orders Screen",
  ORDER_SCREEN: "Order Screen",
  TRANSACTIONS_SCREEN: "Transactions Screen",
  PAYMENTS_SCREEN: "Payments Screen",
  PAYMENT_SCREEN: "Payment Screen",
  PRODUCT_NAVIGATION: "Product nav",
  PRODUCT_SCREEN: "Product Screen",
  PRODUCT_REVIEW_SCREEN: "Review Screen",
});
